import type { Template } from "../_shared";
import { id } from "../_shared";

// ─────────────────────────────────────────────────────────────────────────────
//  Golden Hour — luxury brand / premium promo
// ─────────────────────────────────────────────────────────────────────────────
export const goldenHour: Template = {
  id: "golden-hour",
  name: "Golden Hour",
  description:
    "Opulent gold & dark design for luxury brands, premium giveaways and exclusive promotions.",
  category: "promo",
  tags: ["Promo", "Luxury", "Brand", "Premium"],
  previewGradient: "linear-gradient(160deg, #140900 0%, #291200 100%)",
  accentColor: "#d4a017",
  snapshot: {
    version: 1,
    defaultW: 320,
    defaultH: 480,
    currentPreviewIndex: 0,
    quizData: {
      bg: null,
      frames: [
        // ── Frame 1 — Intro ──────────────────────────────────────────────────
        {
          id: id("gh-f1"),
          src: null,
          w: 320,
          h: 480,
          isDefault: true,
          isEndFrame: false,
          bgGradient: { angle: 160, stops: ["#130800", "#251100"] },
          animEnter: { type: "blsFadeIn", dur: 600 },
          animExit: { type: "blsFadeOut", dur: 400 },
          answerStagger: 100,
          objects: [
            {
              id: id("gh-f1-o1"),
              type: "shape",
              shape: "rect",
              label: "Gold Bar Top",
              x: 0,
              y: 0,
              w: 320,
              h: 3,
              fill: "#d4a017",
            },
            {
              id: id("gh-f1-o2"),
              type: "shape",
              shape: "rect",
              label: "Gold Bar Bottom",
              x: 0,
              y: 477,
              w: 320,
              h: 3,
              fill: "#d4a017",
            },
            {
              id: id("gh-f1-o3"),
              type: "shape",
              shape: "rect",
              label: "Gold Bar Left",
              x: 0,
              y: 0,
              w: 3,
              h: 480,
              fill: "#d4a017",
            },
            {
              id: id("gh-f1-o4"),
              type: "shape",
              shape: "rect",
              label: "Gold Bar Right",
              x: 317,
              y: 0,
              w: 3,
              h: 480,
              fill: "#d4a017",
            },
            {
              id: id("gh-f1-o5"),
              type: "shape",
              shape: "circle",
              label: "Circle Deco 1",
              x: 80,
              y: 60,
              w: 160,
              h: 160,
              fill: "rgba(212,160,23,0.07)",
            },
            {
              id: id("gh-f1-o6"),
              type: "shape",
              shape: "circle",
              label: "Circle Ring",
              x: 70,
              y: 50,
              w: 180,
              h: 180,
              fill: "rgba(212,160,23,0.03)",
              stroke: "rgba(212,160,23,0.25)",
              strokeWidth: 1,
            },
            {
              id: id("gh-f1-o7"),
              type: "text",
              label: "Brand Tag",
              text: "EXCLUSIVE OFFER",
              x: 0,
              y: 42,
              size: 10,
              color: "#d4a017",
              textAlign: "center",
              letterSpacing: 5,
              fontWeight: "700",
              animIn: { type: "blsFadeIn", dur: 500, delay: 0 },
            },
            {
              id: id("gh-f1-o8"),
              type: "text",
              label: "Headline",
              text: "WIN A\nLUXURY\nGETAWAY",
              x: 0,
              y: 90,
              size: 56,
              color: "#f5e0a0",
              textAlign: "center",
              fontWeight: "900",
              lineHeight: 1.0,
              letterSpacing: 2,
              animIn: { type: "blsSlideUp", dur: 600, delay: 150 },
            },
            {
              id: id("gh-f1-o9"),
              type: "divider",
              label: "Gold Rule",
              x: 90,
              y: 290,
              w: 140,
              thickness: 1,
              color: "#d4a017",
              lineStyle: "solid",
            },
            {
              id: id("gh-f1-o10"),
              type: "text",
              label: "Sub copy",
              text: "Answer correctly for\na chance to enter",
              x: 30,
              y: 305,
              size: 14,
              color: "rgba(210,170,80,0.7)",
              textAlign: "center",
              lineHeight: 1.5,
              animIn: { type: "blsFadeIn", dur: 500, delay: 400 },
            },
            {
              id: id("gh-f1-o11"),
              type: "text",
              label: "Deco Row",
              text: "◇  ◆  ◇",
              x: 0,
              y: 358,
              size: 20,
              color: "rgba(212,160,23,0.5)",
              textAlign: "center",
            },
            {
              id: id("gh-f1-o12"),
              type: "shape",
              shape: "rect",
              label: "CTA BG",
              x: 70,
              y: 406,
              w: 180,
              h: 50,
              fill: "#d4a017",
              radius: 25,
            },
            {
              id: id("gh-f1-o13"),
              type: "text",
              label: "CTA Text",
              text: "ENTER NOW",
              x: 70,
              y: 419,
              size: 14,
              color: "#130800",
              textAlign: "center",
              fontWeight: "900",
              letterSpacing: 3,
              animIn: { type: "blsFadeIn", dur: 400, delay: 600 },
            },
          ],
        },
        // ── Frame 2 — Question ───────────────────────────────────────────────
        {
          id: id("gh-f2"),
          src: null,
          w: 320,
          h: 480,
          isDefault: false,
          isEndFrame: false,
          bgGradient: { angle: 160, stops: ["#130800", "#251100"] },
          animEnter: { type: "blsFadeIn", dur: 450 },
          animExit: { type: "blsFadeOut", dur: 300 },
          answerStagger: 100,
          objects: [
            {
              id: id("gh-f2-o1"),
              type: "shape",
              shape: "rect",
              label: "Gold Bar Top",
              x: 0,
              y: 0,
              w: 320,
              h: 3,
              fill: "#d4a017",
            },
            {
              id: id("gh-f2-o2"),
              type: "shape",
              shape: "rect",
              label: "Gold Bar Bottom",
              x: 0,
              y: 477,
              w: 320,
              h: 3,
              fill: "#d4a017",
            },
            {
              id: id("gh-f2-o3"),
              type: "text",
              label: "Header Tag",
              text: "▸  QUALIFYING QUESTION",
              x: 20,
              y: 22,
              size: 10,
              color: "#d4a017",
              letterSpacing: 3,
              fontWeight: "700",
              animIn: { type: "blsFadeIn", dur: 300 },
            },
            {
              id: id("gh-f2-o4"),
              type: "divider",
              label: "Gold Divider",
              x: 20,
              y: 44,
              w: 280,
              thickness: 1,
              color: "rgba(212,160,23,0.3)",
              lineStyle: "solid",
            },
            {
              id: id("gh-f2-o5"),
              type: "text",
              label: "Q Intro",
              text: "To enter the draw,\nplease answer:",
              x: 20,
              y: 60,
              size: 14,
              color: "rgba(200,160,70,0.65)",
              lineHeight: 1.5,
              animIn: { type: "blsFadeIn", dur: 400, delay: 50 },
            },
            {
              id: id("gh-f2-o6"),
              type: "text",
              label: "Question",
              text: 'Which destination is\nknown as the\n"City of Light"?',
              x: 20,
              y: 112,
              size: 26,
              color: "#f5e0a0",
              fontWeight: "800",
              lineHeight: 1.25,
              animIn: { type: "blsSlideUp", dur: 500, delay: 150 },
            },
            {
              id: id("gh-f2-o7"),
              type: "divider",
              label: "Mid Divider",
              x: 20,
              y: 238,
              w: 280,
              thickness: 1,
              color: "rgba(212,160,23,0.2)",
              lineStyle: "dashed",
            },
            {
              id: id("gh-f2-o8"),
              type: "answerGroup",
              label: "Answers",
              x: 20,
              y: 254,
              w: 280,
              answers: [
                { id: id("gh-f2-a1"), text: "London" },
                { id: id("gh-f2-a2"), text: "Paris" },
                { id: id("gh-f2-a3"), text: "Rome" },
                { id: id("gh-f2-a4"), text: "Milan" },
              ],
              btnHeight: 46,
              btnGap: 10,
              btnBgColor: "#d4a017",
              btnBgOpacity: 14,
              btnRadius: 8,
              textColor: "#f5e0a0",
              fontSize: 15,
              role: "answer",
              animIn: { type: "blsSlideUp", dur: 500, delay: 250 },
              animOut: { type: "blsFadeOut", dur: 300, delay: 0 },
            },
          ],
        },
      ],
    },
  },
};
