import type { Template } from "../_shared";
import { id } from "../_shared";

// ─────────────────────────────────────────────────────────────────────────────
//  Solar Flare — high-urgency / breaking news / live event
// ─────────────────────────────────────────────────────────────────────────────
export const solarFlare: Template = {
  id: "solar-flare",
  name: "Solar Flare",
  description:
    "Fiery orange & dark design for live events, breaking polls and time-sensitive campaigns.",
  category: "news",
  tags: ["Live", "News", "Urgent", "Event"],
  previewGradient: "linear-gradient(160deg, #0d0200 0%, #1f0700 100%)",
  accentColor: "#f97316",
  snapshot: {
    version: 1,
    defaultW: 320,
    defaultH: 480,
    currentPreviewIndex: 0,
    quizData: {
      bg: null,
      frames: [
        // ── Frame 1 — Live Intro ─────────────────────────────────────────────
        {
          id: id("sf-f1"),
          src: null,
          w: 320,
          h: 480,
          isDefault: true,
          isEndFrame: false,
          bgGradient: { angle: 160, stops: ["#0d0200", "#1f0700"] },
          animEnter: { type: "blsFadeIn", dur: 400 },
          animExit: { type: "blsFadeOut", dur: 300 },
          answerStagger: 70,
          objects: [
            {
              id: id("sf-f1-o1"),
              type: "shape",
              shape: "rect",
              label: "Top Bar",
              x: 0,
              y: 0,
              w: 320,
              h: 5,
              fill: "#f97316",
            },
            {
              id: id("sf-f1-o2"),
              type: "shape",
              shape: "rect",
              label: "Live BG",
              x: 20,
              y: 18,
              w: 48,
              h: 22,
              fill: "#ef4444",
              radius: 3,
            },
            {
              id: id("sf-f1-o3"),
              type: "text",
              label: "Live Badge",
              text: "● LIVE",
              x: 20,
              y: 21,
              size: 10,
              color: "#ffffff",
              fontWeight: "900",
              letterSpacing: 1,
            },
            {
              id: id("sf-f1-o4"),
              type: "text",
              label: "Event Tag",
              text: "BREAKING POLL",
              x: 80,
              y: 22,
              size: 10,
              color: "rgba(255,120,50,0.7)",
              letterSpacing: 3,
              fontWeight: "700",
            },
            {
              id: id("sf-f1-o5"),
              type: "divider",
              label: "Divider 1",
              x: 0,
              y: 50,
              w: 320,
              thickness: 1,
              color: "rgba(249,115,22,0.2)",
              lineStyle: "solid",
            },
            {
              id: id("sf-f1-o6"),
              type: "shape",
              shape: "circle",
              label: "Glow",
              x: 60,
              y: 80,
              w: 200,
              h: 200,
              fill: "rgba(249,115,22,0.07)",
            },
            {
              id: id("sf-f1-o7"),
              type: "text",
              label: "Headline 1",
              text: "WHO WILL",
              x: 0,
              y: 110,
              size: 44,
              color: "rgba(255,255,255,0.85)",
              textAlign: "center",
              fontWeight: "900",
              letterSpacing: 0,
              animIn: { type: "blsSlideUp", dur: 400, delay: 50 },
            },
            {
              id: id("sf-f1-o8"),
              type: "text",
              label: "Headline 2",
              text: "WIN\nTONIGHT?",
              x: 0,
              y: 155,
              size: 58,
              color: "#f97316",
              textAlign: "center",
              fontWeight: "900",
              lineHeight: 1.0,
              letterSpacing: -1,
              animIn: { type: "blsSlideUp", dur: 500, delay: 130 },
            },
            {
              id: id("sf-f1-o9"),
              type: "divider",
              label: "Divider 2",
              x: 40,
              y: 290,
              w: 240,
              thickness: 2,
              color: "rgba(249,115,22,0.35)",
              lineStyle: "solid",
            },
            {
              id: id("sf-f1-o10"),
              type: "text",
              label: "Subtext",
              text: "CAST YOUR VOTE NOW",
              x: 0,
              y: 302,
              size: 13,
              color: "rgba(255,200,100,0.55)",
              textAlign: "center",
              letterSpacing: 3,
              fontWeight: "700",
              animIn: { type: "blsFadeIn", dur: 400, delay: 300 },
            },
            {
              id: id("sf-f1-o11"),
              type: "answerGroup",
              label: "Answers",
              x: 20,
              y: 330,
              w: 280,
              answers: [
                { id: id("sf-f1-a1"), text: "Team Alpha" },
                { id: id("sf-f1-a2"), text: "Team Omega" },
                { id: id("sf-f1-a3"), text: "Too close to call" },
              ],
              btnHeight: 42,
              btnGap: 10,
              btnBgColor: "#f97316",
              btnBgOpacity: 16,
              btnRadius: 6,
              textColor: "#fff7ed",
              fontSize: 15,
              role: "poll",
              animIn: { type: "blsSlideUp", dur: 400, delay: 250 },
              animOut: { type: "blsFadeOut", dur: 300, delay: 0 },
            },
          ],
        },
        // ── Frame 2 — Follow-up question ─────────────────────────────────────
        {
          id: id("sf-f2"),
          src: null,
          w: 320,
          h: 480,
          isDefault: false,
          isEndFrame: false,
          bgGradient: { angle: 160, stops: ["#0d0200", "#1f0700"] },
          animEnter: { type: "blsSlideUp", dur: 380 },
          animExit: { type: "blsFadeOut", dur: 280 },
          answerStagger: 70,
          objects: [
            {
              id: id("sf-f2-o1"),
              type: "shape",
              shape: "rect",
              label: "Top Bar",
              x: 0,
              y: 0,
              w: 320,
              h: 5,
              fill: "#f97316",
            },
            {
              id: id("sf-f2-o2"),
              type: "shape",
              shape: "rect",
              label: "Live BG",
              x: 20,
              y: 18,
              w: 48,
              h: 22,
              fill: "#ef4444",
              radius: 3,
            },
            {
              id: id("sf-f2-o3"),
              type: "text",
              label: "Live Badge",
              text: "● LIVE",
              x: 20,
              y: 21,
              size: 10,
              color: "#ffffff",
              fontWeight: "900",
              letterSpacing: 1,
            },
            {
              id: id("sf-f2-o4"),
              type: "divider",
              label: "Divider",
              x: 0,
              y: 50,
              w: 320,
              thickness: 1,
              color: "rgba(249,115,22,0.2)",
              lineStyle: "solid",
            },
            {
              id: id("sf-f2-o5"),
              type: "shape",
              shape: "circle",
              label: "Glow",
              x: 100,
              y: 0,
              w: 180,
              h: 180,
              fill: "rgba(249,115,22,0.06)",
            },
            {
              id: id("sf-f2-o6"),
              type: "text",
              label: "Q Counter",
              text: "QUESTION 2 / 2",
              x: 0,
              y: 60,
              size: 10,
              color: "#f97316",
              textAlign: "center",
              letterSpacing: 3,
              fontWeight: "700",
              animIn: { type: "blsFadeIn", dur: 300 },
            },
            {
              id: id("sf-f2-o7"),
              type: "text",
              label: "Question",
              text: "By how many points\nwill the winner\nneed to lead?",
              x: 20,
              y: 86,
              size: 26,
              color: "#ffffff",
              fontWeight: "800",
              lineHeight: 1.25,
              animIn: { type: "blsSlideUp", dur: 430, delay: 100 },
            },
            {
              id: id("sf-f2-o8"),
              type: "divider",
              label: "Mid Divider",
              x: 20,
              y: 232,
              w: 280,
              thickness: 1,
              color: "rgba(249,115,22,0.25)",
              lineStyle: "dashed",
            },
            {
              id: id("sf-f2-o9"),
              type: "answerGroup",
              label: "Answers",
              x: 20,
              y: 250,
              w: 280,
              answers: [
                { id: id("sf-f2-a1"), text: "1–5 points" },
                { id: id("sf-f2-a2"), text: "6–10 points" },
                { id: id("sf-f2-a3"), text: "11–20 points" },
                { id: id("sf-f2-a4"), text: "20+ points" },
              ],
              btnHeight: 44,
              btnGap: 10,
              btnBgColor: "#f97316",
              btnBgOpacity: 16,
              btnRadius: 6,
              textColor: "#fff7ed",
              fontSize: 15,
              role: "poll",
              animIn: { type: "blsSlideUp", dur: 420, delay: 200 },
              animOut: { type: "blsFadeOut", dur: 280, delay: 0 },
            },
          ],
        },
      ],
    },
  },
};
