import type { Template } from "../_shared";
import { id } from "../_shared";

// ─────────────────────────────────────────────────────────────────────────────
//  Sport Blitz — high-energy sports quiz
// ─────────────────────────────────────────────────────────────────────────────
export const sportBlitz: Template = {
  id: "sport-blitz",
  name: "Sport Blitz",
  description:
    "High-octane red & black design for sports trivia and match-day polls.",
  category: "sport",
  tags: ["Sport", "Quiz", "Bold", "Dark"],
  previewGradient: "linear-gradient(160deg, #0f0000 0%, #200a00 100%)",
  accentColor: "#ff2d55",
  snapshot: {
    version: 1,
    defaultW: 320,
    defaultH: 480,
    currentPreviewIndex: 0,
    quizData: {
      bg: null,
      frames: [
        // ── Frame 1 — Intro ──────────────────────────────────────────────────
        {
          id: id("sb-f1"),
          src: null,
          w: 320,
          h: 480,
          isDefault: true,
          isEndFrame: false,
          bgGradient: { angle: 160, stops: ["#0c0000", "#1c0800"] },
          animEnter: { type: "blsFadeIn", dur: 450 },
          animExit: { type: "blsFadeOut", dur: 300 },
          answerStagger: 70,
          objects: [
            {
              id: id("sb-f1-o1"),
              type: "shape",
              shape: "rect",
              label: "Top Bar",
              x: 0,
              y: 0,
              w: 320,
              h: 6,
              fill: "#ff2d55",
            },
            {
              id: id("sb-f1-o2"),
              type: "shape",
              shape: "rect",
              label: "Hero BG Block",
              x: 0,
              y: 0,
              w: 320,
              h: 200,
              fill: "rgba(255,45,85,0.08)",
            },
            {
              id: id("sb-f1-o3"),
              type: "shape",
              shape: "circle",
              label: "Circle Deco",
              x: 200,
              y: 30,
              w: 160,
              h: 160,
              fill: "rgba(255,45,85,0.06)",
            },
            {
              id: id("sb-f1-o4"),
              type: "text",
              label: "Tag",
              text: "◆  SPORTS TRIVIA  ◆",
              x: 0,
              y: 100,
              size: 11,
              color: "#ff2d55",
              textAlign: "center",
              letterSpacing: 3,
              fontWeight: "700",
              animIn: { type: "blsFadeIn", dur: 400, delay: 0 },
            },
            {
              id: id("sb-f1-o5"),
              type: "text",
              label: "Headline 1",
              text: "SPORT",
              x: 0,
              y: 128,
              size: 80,
              color: "#ffffff",
              textAlign: "center",
              fontWeight: "900",
              letterSpacing: -1,
              animIn: { type: "blsSlideUp", dur: 500, delay: 100 },
            },
            {
              id: id("sb-f1-o6"),
              type: "text",
              label: "Headline 2",
              text: "BLITZ",
              x: 0,
              y: 212,
              size: 80,
              color: "#ff2d55",
              textAlign: "center",
              fontWeight: "900",
              letterSpacing: -1,
              animIn: { type: "blsSlideUp", dur: 500, delay: 200 },
            },
            {
              id: id("sb-f1-o7"),
              type: "divider",
              label: "Divider",
              x: 40,
              y: 302,
              w: 240,
              thickness: 2,
              color: "rgba(255,45,85,0.4)",
              lineStyle: "solid",
            },
            {
              id: id("sb-f1-o8"),
              type: "text",
              label: "Promo",
              text: "3 ROUNDS · WIN EXCLUSIVE MERCH",
              x: 0,
              y: 315,
              size: 11,
              color: "rgba(255,255,255,0.45)",
              textAlign: "center",
              letterSpacing: 2,
              animIn: { type: "blsFadeIn", dur: 400, delay: 350 },
            },
            {
              id: id("sb-f1-o9"),
              type: "shape",
              shape: "rect",
              label: "CTA BG",
              x: 80,
              y: 408,
              w: 160,
              h: 46,
              fill: "#ff2d55",
              radius: 23,
            },
            {
              id: id("sb-f1-o10"),
              type: "text",
              label: "CTA Text",
              text: "PLAY NOW",
              x: 80,
              y: 420,
              size: 14,
              color: "#ffffff",
              textAlign: "center",
              fontWeight: "900",
              letterSpacing: 3,
              animIn: { type: "blsFadeIn", dur: 400, delay: 500 },
            },
          ],
        },
        // ── Frame 2 — Question ───────────────────────────────────────────────
        {
          id: id("sb-f2"),
          src: null,
          w: 320,
          h: 480,
          isDefault: false,
          isEndFrame: false,
          bgGradient: { angle: 160, stops: ["#0c0000", "#1c0800"] },
          animEnter: { type: "blsSlideUp", dur: 400 },
          animExit: { type: "blsFadeOut", dur: 300 },
          answerStagger: 80,
          objects: [
            {
              id: id("sb-f2-o1"),
              type: "shape",
              shape: "rect",
              label: "Top Bar",
              x: 0,
              y: 0,
              w: 320,
              h: 5,
              fill: "#ff2d55",
            },
            {
              id: id("sb-f2-o2"),
              type: "shape",
              shape: "rect",
              label: "Score Badge BG",
              x: 20,
              y: 16,
              w: 68,
              h: 24,
              fill: "#ff2d55",
              radius: 4,
            },
            {
              id: id("sb-f2-o3"),
              type: "text",
              label: "Round Badge",
              text: "ROUND 1",
              x: 20,
              y: 19,
              size: 10,
              color: "#ffffff",
              fontWeight: "900",
              letterSpacing: 2,
              animIn: { type: "blsFadeIn", dur: 300 },
            },
            {
              id: id("sb-f2-o4"),
              type: "text",
              label: "Q Index",
              text: "Q1 / 5",
              x: 240,
              y: 20,
              size: 11,
              color: "rgba(255,255,255,0.4)",
              fontWeight: "700",
              letterSpacing: 1,
            },
            {
              id: id("sb-f2-o5"),
              type: "divider",
              label: "Divider",
              x: 20,
              y: 50,
              w: 280,
              thickness: 1,
              color: "rgba(255,45,85,0.25)",
              lineStyle: "solid",
            },
            {
              id: id("sb-f2-o6"),
              type: "text",
              label: "Question",
              text: "How many players are\nthere in a standard\nfootball team?",
              x: 20,
              y: 68,
              size: 24,
              color: "#ffffff",
              fontWeight: "800",
              lineHeight: 1.3,
              animIn: { type: "blsSlideUp", dur: 450, delay: 80 },
            },
            {
              id: id("sb-f2-o7"),
              type: "answerGroup",
              label: "Answers",
              x: 20,
              y: 234,
              w: 280,
              answers: [
                { id: id("sb-f2-a1"), text: "9 players" },
                { id: id("sb-f2-a2"), text: "11 players" },
                { id: id("sb-f2-a3"), text: "13 players" },
                { id: id("sb-f2-a4"), text: "15 players" },
              ],
              btnHeight: 46,
              btnGap: 10,
              btnBgColor: "#ff2d55",
              btnBgOpacity: 14,
              btnRadius: 8,
              textColor: "#ffffff",
              fontSize: 15,
              role: "answer",
              animIn: { type: "blsSlideUp", dur: 400, delay: 200 },
              animOut: { type: "blsFadeOut", dur: 300, delay: 0 },
            },
          ],
        },
      ],
    },
  },
};
