/**
 * Comprehensive list of popular Google Fonts.
 * Source: Google Fonts catalog – top fonts by popularity + broad category coverage.
 * Each entry: { family, category }
 * category values: sans-serif | serif | display | handwriting | monospace
 */
export interface GoogleFontMeta {
  family: string;
  category: "sans-serif" | "serif" | "display" | "handwriting" | "monospace";
}

export const GOOGLE_FONTS: GoogleFontMeta[] = [
  // ── Sans-serif ────────────────────────────────────────────────────────────
  { family: "Inter", category: "sans-serif" },
  { family: "Roboto", category: "sans-serif" },
  { family: "Open Sans", category: "sans-serif" },
  { family: "Lato", category: "sans-serif" },
  { family: "Montserrat", category: "sans-serif" },
  { family: "Poppins", category: "sans-serif" },
  { family: "Nunito", category: "sans-serif" },
  { family: "Raleway", category: "sans-serif" },
  { family: "Ubuntu", category: "sans-serif" },
  { family: "Cabin", category: "sans-serif" },
  { family: "Karla", category: "sans-serif" },
  { family: "Mulish", category: "sans-serif" },
  { family: "Barlow", category: "sans-serif" },
  { family: "Barlow Condensed", category: "sans-serif" },
  { family: "Figtree", category: "sans-serif" },
  { family: "DM Sans", category: "sans-serif" },
  { family: "Outfit", category: "sans-serif" },
  { family: "Plus Jakarta Sans", category: "sans-serif" },
  { family: "Manrope", category: "sans-serif" },
  { family: "Jost", category: "sans-serif" },
  { family: "Rubik", category: "sans-serif" },
  { family: "Work Sans", category: "sans-serif" },
  { family: "Lexend", category: "sans-serif" },
  { family: "Source Sans 3", category: "sans-serif" },
  { family: "PT Sans", category: "sans-serif" },
  { family: "PT Sans Narrow", category: "sans-serif" },
  { family: "Noto Sans", category: "sans-serif" },
  { family: "Josefin Sans", category: "sans-serif" },
  { family: "Nunito Sans", category: "sans-serif" },
  { family: "Quicksand", category: "sans-serif" },
  { family: "Hind", category: "sans-serif" },
  { family: "IBM Plex Sans", category: "sans-serif" },
  { family: "Exo 2", category: "sans-serif" },
  { family: "Exo", category: "sans-serif" },
  { family: "Varela Round", category: "sans-serif" },
  { family: "Titillium Web", category: "sans-serif" },
  { family: "Space Grotesk", category: "sans-serif" },
  { family: "Epilogue", category: "sans-serif" },
  { family: "Urbanist", category: "sans-serif" },
  { family: "Sora", category: "sans-serif" },
  { family: "Hind Siliguri", category: "sans-serif" },
  { family: "Nanum Gothic", category: "sans-serif" },
  { family: "Mada", category: "sans-serif" },
  { family: "Maven Pro", category: "sans-serif" },
  { family: "Gudea", category: "sans-serif" },
  { family: "Oxygen", category: "sans-serif" },
  { family: "Overpass", category: "sans-serif" },
  { family: "Kanit", category: "sans-serif" },
  { family: "Prompt", category: "sans-serif" },
  { family: "Heebo", category: "sans-serif" },
  { family: "Catamaran", category: "sans-serif" },
  { family: "Asap", category: "sans-serif" },
  { family: "Arimo", category: "sans-serif" },
  { family: "Public Sans", category: "sans-serif" },
  { family: "Red Hat Display", category: "sans-serif" },
  { family: "Red Hat Text", category: "sans-serif" },
  { family: "Albert Sans", category: "sans-serif" },
  { family: "Be Vietnam Pro", category: "sans-serif" },
  { family: "Fira Sans", category: "sans-serif" },
  { family: "Fira Sans Condensed", category: "sans-serif" },
  { family: "Signika", category: "sans-serif" },
  { family: "Chivo", category: "sans-serif" },
  { family: "Alata", category: "sans-serif" },
  { family: "Saira", category: "sans-serif" },
  { family: "Saira Condensed", category: "sans-serif" },
  { family: "Teko", category: "sans-serif" },
  { family: "Encode Sans", category: "sans-serif" },
  { family: "M PLUS Rounded 1c", category: "sans-serif" },
  { family: "Noto Sans JP", category: "sans-serif" },
  // ── Serif ─────────────────────────────────────────────────────────────────
  { family: "Merriweather", category: "serif" },
  { family: "Playfair Display", category: "serif" },
  { family: "Lora", category: "serif" },
  { family: "PT Serif", category: "serif" },
  { family: "Source Serif 4", category: "serif" },
  { family: "Crimson Text", category: "serif" },
  { family: "EB Garamond", category: "serif" },
  { family: "Cormorant Garamond", category: "serif" },
  { family: "Libre Baskerville", category: "serif" },
  { family: "Noto Serif", category: "serif" },
  { family: "IBM Plex Serif", category: "serif" },
  { family: "Spectral", category: "serif" },
  { family: "Bitter", category: "serif" },
  { family: "Volkhov", category: "serif" },
  { family: "Arvo", category: "serif" },
  { family: "Domine", category: "serif" },
  { family: "Zilla Slab", category: "serif" },
  { family: "Cardo", category: "serif" },
  { family: "Frank Ruhl Libre", category: "serif" },
  { family: "Tinos", category: "serif" },
  { family: "Rokkitt", category: "serif" },
  { family: "Abril Fatface", category: "display" },
  // ── Display ───────────────────────────────────────────────────────────────
  { family: "Oswald", category: "display" },
  { family: "Anton", category: "display" },
  { family: "Bebas Neue", category: "display" },
  { family: "Righteous", category: "display" },
  { family: "Black Han Sans", category: "display" },
  { family: "Fredoka One", category: "display" },
  { family: "Staatliches", category: "display" },
  { family: "Bangers", category: "display" },
  { family: "Alfa Slab One", category: "display" },
  { family: "Boogaloo", category: "display" },
  { family: "Patua One", category: "display" },
  { family: "Lilita One", category: "display" },
  { family: "Archivo Black", category: "display" },
  { family: "Archivo Narrow", category: "sans-serif" },
  { family: "Graduate", category: "display" },
  { family: "Dela Gothic One", category: "display" },
  { family: "Big Shoulders Display", category: "display" },
  { family: "Big Shoulders Text", category: "display" },
  { family: "Passion One", category: "display" },
  { family: "Bree Serif", category: "serif" },
  { family: "Ultra", category: "serif" },
  { family: "Lobster", category: "display" },
  { family: "Lobster Two", category: "display" },
  { family: "Titan One", category: "display" },
  { family: "Squada One", category: "display" },
  { family: "Russo One", category: "display" },
  { family: "Teko", category: "display" },
  { family: "Fugaz One", category: "display" },
  { family: "Racing Sans One", category: "display" },
  { family: "Bungee", category: "display" },
  { family: "Bungee Inline", category: "display" },
  { family: "Norwester", category: "display" },
  { family: "Secular One", category: "sans-serif" },
  { family: "Syne", category: "sans-serif" },
  { family: "Syne Mono", category: "monospace" },
  { family: "Permanent Marker", category: "handwriting" },
  { family: "Black Ops One", category: "display" },
  { family: "Michroma", category: "sans-serif" },
  { family: "Orbitron", category: "display" },
  { family: "Rajdhani", category: "sans-serif" },
  { family: "Chakra Petch", category: "sans-serif" },
  { family: "Audiowide", category: "display" },
  { family: "Electrolize", category: "sans-serif" },
  { family: "Share Tech Mono", category: "monospace" },
  { family: "Nova Square", category: "display" },
  { family: "Syncopate", category: "display" },
  { family: "Rationale", category: "sans-serif" },
  { family: "Iceland", category: "display" },
  { family: "Conthrax", category: "sans-serif" },
  { family: "Press Start 2P", category: "display" },
  { family: "VT323", category: "monospace" },
  // ── Handwriting ───────────────────────────────────────────────────────────
  { family: "Dancing Script", category: "handwriting" },
  { family: "Pacifico", category: "handwriting" },
  { family: "Caveat", category: "handwriting" },
  { family: "Satisfy", category: "handwriting" },
  { family: "Kaushan Script", category: "handwriting" },
  { family: "Courgette", category: "handwriting" },
  { family: "Cookie", category: "handwriting" },
  { family: "Great Vibes", category: "handwriting" },
  { family: "Sacramento", category: "handwriting" },
  { family: "Alex Brush", category: "handwriting" },
  { family: "Allura", category: "handwriting" },
  { family: "Pinyon Script", category: "handwriting" },
  { family: "Italianno", category: "handwriting" },
  { family: "Tangerine", category: "handwriting" },
  { family: "Euphoria Script", category: "handwriting" },
  { family: "Mr Dafoe", category: "handwriting" },
  { family: "Amatic SC", category: "handwriting" },
  { family: "Shadows Into Light", category: "handwriting" },
  { family: "Indie Flower", category: "handwriting" },
  { family: "Patrick Hand", category: "handwriting" },
  { family: "Architects Daughter", category: "handwriting" },
  { family: "Rock Salt", category: "handwriting" },
  { family: "Homemade Apple", category: "handwriting" },
  { family: "Marck Script", category: "handwriting" },
  { family: "Handlee", category: "handwriting" },
  { family: "Loved by the King", category: "handwriting" },
  { family: "Oswald", category: "display" },
  // ── Monospace ─────────────────────────────────────────────────────────────
  { family: "Roboto Mono", category: "monospace" },
  { family: "Source Code Pro", category: "monospace" },
  { family: "JetBrains Mono", category: "monospace" },
  { family: "IBM Plex Mono", category: "monospace" },
  { family: "Space Mono", category: "monospace" },
  { family: "Fira Mono", category: "monospace" },
  { family: "Inconsolata", category: "monospace" },
  { family: "Cousine", category: "monospace" },
  { family: "Nanum Gothic Coding", category: "monospace" },
  { family: "Anonymous Pro", category: "monospace" },
  { family: "Cutive Mono", category: "monospace" },
  { family: "Overpass Mono", category: "monospace" },
  { family: "DM Mono", category: "monospace" },
  { family: "Major Mono Display", category: "monospace" },
  { family: "Courier Prime", category: "monospace" },
  { family: "Nova Mono", category: "monospace" },
];

/** Deduplicated, sorted A→Z within each category. */
export const GOOGLE_FONTS_SORTED = [
  ...new Map(GOOGLE_FONTS.map((f) => [f.family, f])).values(),
].sort(
  (a, b) =>
    a.category.localeCompare(b.category) || a.family.localeCompare(b.family),
);

/** Just the family names, alphabetical – for fast text search. */
export const GOOGLE_FONT_NAMES: string[] = [
  ...new Set(GOOGLE_FONTS.map((f) => f.family)),
].sort();
