import type { Template } from "../_shared";
import { id } from "../_shared";

// ─────────────────────────────────────────────────────────────────────────────
//  Arctic Pro — clean professional poll / survey
// ─────────────────────────────────────────────────────────────────────────────
export const arcticPro: Template = {
  id: "arctic-pro",
  name: "Arctic Pro",
  description:
    "Clean, professional blue & white layout for brand polls, surveys and product feedback.",
  category: "poll",
  tags: ["Poll", "Clean", "Professional", "Survey"],
  previewGradient: "linear-gradient(135deg, #0f172a 0%, #1e3a5f 100%)",
  accentColor: "#3b82f6",
  snapshot: {
    version: 1,
    defaultW: 320,
    defaultH: 480,
    currentPreviewIndex: 0,
    quizData: {
      bg: null,
      frames: [
        // ── Frame 1 — Poll ───────────────────────────────────────────────────
        {
          id: id("ap-f1"),
          src: null,
          w: 320,
          h: 480,
          isDefault: true,
          isEndFrame: false,
          bgGradient: { angle: 140, stops: ["#0f172a", "#1e3a5f"] },
          animEnter: { type: "blsFadeIn", dur: 500 },
          animExit: { type: "blsFadeOut", dur: 350 },
          answerStagger: 90,
          objects: [
            {
              id: id("ap-f1-o1"),
              type: "shape",
              shape: "rect",
              label: "Header BG",
              x: 0,
              y: 0,
              w: 320,
              h: 130,
              fill: "rgba(59,130,246,0.12)",
            },
            {
              id: id("ap-f1-o2"),
              type: "shape",
              shape: "rect",
              label: "Blue Top Bar",
              x: 0,
              y: 0,
              w: 320,
              h: 4,
              fill: "#3b82f6",
            },
            {
              id: id("ap-f1-o3"),
              type: "shape",
              shape: "circle",
              label: "Logo BG",
              x: 130,
              y: 30,
              w: 60,
              h: 60,
              fill: "rgba(59,130,246,0.2)",
              stroke: "#3b82f6",
              strokeWidth: 2,
            },
            {
              id: id("ap-f1-o4"),
              type: "text",
              label: "Logo Text",
              text: "BLS",
              x: 130,
              y: 48,
              size: 16,
              color: "#3b82f6",
              textAlign: "center",
              fontWeight: "900",
              letterSpacing: 2,
            },
            {
              id: id("ap-f1-o5"),
              type: "text",
              label: "Brand Name",
              text: "BRAND NAME",
              x: 0,
              y: 106,
              size: 11,
              color: "rgba(255,255,255,0.4)",
              textAlign: "center",
              letterSpacing: 4,
              fontWeight: "600",
            },
            {
              id: id("ap-f1-o6"),
              type: "divider",
              label: "Divider 1",
              x: 20,
              y: 140,
              w: 280,
              thickness: 1,
              color: "rgba(59,130,246,0.25)",
              lineStyle: "solid",
            },
            {
              id: id("ap-f1-o7"),
              type: "text",
              label: "Poll Intro",
              text: "QUICK POLL",
              x: 0,
              y: 158,
              size: 12,
              color: "#93c5fd",
              textAlign: "center",
              letterSpacing: 4,
              fontWeight: "700",
              animIn: { type: "blsFadeIn", dur: 400, delay: 0 },
            },
            {
              id: id("ap-f1-o8"),
              type: "text",
              label: "Question",
              text: "What matters most\nwhen choosing\na product?",
              x: 20,
              y: 184,
              size: 26,
              color: "#ffffff",
              textAlign: "center",
              fontWeight: "700",
              lineHeight: 1.3,
              animIn: { type: "blsSlideUp", dur: 500, delay: 150 },
            },
            {
              id: id("ap-f1-o9"),
              type: "divider",
              label: "Divider 2",
              x: 60,
              y: 296,
              w: 200,
              thickness: 1,
              color: "rgba(59,130,246,0.2)",
              lineStyle: "dashed",
            },
            {
              id: id("ap-f1-o10"),
              type: "answerGroup",
              label: "Answers",
              x: 20,
              y: 314,
              w: 280,
              answers: [
                { id: id("ap-f1-a1"), text: "Quality" },
                { id: id("ap-f1-a2"), text: "Price" },
                { id: id("ap-f1-a3"), text: "Brand reputation" },
                { id: id("ap-f1-a4"), text: "Reviews" },
              ],
              btnHeight: 36,
              btnGap: 8,
              btnBgColor: "#3b82f6",
              btnBgOpacity: 15,
              btnRadius: 6,
              textColor: "#e0f2fe",
              fontSize: 14,
              role: "poll",
              animIn: { type: "blsSlideUp", dur: 450, delay: 200 },
              animOut: { type: "blsFadeOut", dur: 300, delay: 0 },
            },
          ],
        },
      ],
    },
  },
};
