import type { Template } from "../_shared";
import { id } from "../_shared";

// ─────────────────────────────────────────────────────────────────────────────
//  Cosmos — deep space aesthetic, 3 questions + thank-you end frame
//  Packed with floating decorations, perspective 3D, loop anims, hover & click
// ─────────────────────────────────────────────────────────────────────────────

const ACCENT = "#a855f7"; // vivid purple
const ACCENT2 = "#38bdf8"; // sky blue
const ACCENT3 = "#f472b6"; // pink

export const cosmos: Template = {
  id: "cosmos",
  name: "Cosmos",
  description:
    "Deep-space aesthetic with perspective 3D animations, floating particle decorations, and glowing accents. 3 questions + thank-you frame.",
  category: "quiz",
  tags: ["Quiz", "Space", "Dark", "3D", "Premium"],
  previewGradient: "linear-gradient(160deg, #050818 0%, #1a0a4a 100%)",
  accentColor: ACCENT,
  snapshot: {
    version: 1,
    defaultW: 320,
    defaultH: 480,
    currentPreviewIndex: 0,
    quizData: {
      bg: null,
      frames: [
        // ═══════════════════════════════════════════════════════════════════
        //  FRAME 1 — Question 1
        // ═══════════════════════════════════════════════════════════════════
        {
          id: id("cos-f1"),
          src: null,
          w: 320,
          h: 480,
          isDefault: true,
          isEndFrame: false,
          bgGradient: { angle: 160, stops: ["#050818", "#0f1b3d"] },
          animEnter: { type: "blsFadeIn", dur: 600 },
          animExit: { type: "blsFadeOut", dur: 350 },
          answerStagger: 100,
          objects: [
            // ── Decorative circles (glow orbs) ──
            {
              id: id("cos-f1-c1"),
              type: "shape" as const,
              shape: "circle" as const,
              label: "Orb Purple",
              x: -40,
              y: -30,
              w: 180,
              h: 180,
              fill: "rgba(168,85,247,0.08)",
              animLoop: { type: "blsFloat", dur: 3000, delay: 0 },
            },
            {
              id: id("cos-f1-c2"),
              type: "shape" as const,
              shape: "circle" as const,
              label: "Orb Blue",
              x: 200,
              y: 320,
              w: 160,
              h: 160,
              fill: "rgba(56,189,248,0.06)",
              animLoop: { type: "blsFloat", dur: 3500, delay: 400 },
            },
            {
              id: id("cos-f1-c3"),
              type: "shape" as const,
              shape: "circle" as const,
              label: "Orb Pink",
              x: 220,
              y: 60,
              w: 100,
              h: 100,
              fill: "rgba(244,114,182,0.05)",
              animLoop: { type: "blsPulseLoop", dur: 2800, delay: 200 },
            },
            // ── Tilted accent bars ──
            {
              id: id("cos-f1-bar1"),
              type: "shape" as const,
              shape: "rect" as const,
              label: "Bar Top",
              x: 0,
              y: 0,
              w: 320,
              h: 3,
              fill: ACCENT,
              animIn: { type: "blsSlideRight", dur: 600, delay: 0 },
            },
            {
              id: id("cos-f1-bar2"),
              type: "shape" as const,
              shape: "rect" as const,
              label: "Bar Bottom",
              x: 0,
              y: 477,
              w: 320,
              h: 3,
              fill: ACCENT2,
              animIn: { type: "blsSlideLeft", dur: 600, delay: 0 },
            },
            {
              id: id("cos-f1-bar3"),
              type: "shape" as const,
              shape: "rect" as const,
              label: "Diagonal Accent",
              x: 260,
              y: 10,
              w: 60,
              h: 3,
              fill: ACCENT3,
              rotation: 45,
              opacity: 50,
              animIn: { type: "blsFadeIn", dur: 500, delay: 300 },
            },
            // ── Floating unicode particles ──
            {
              id: id("cos-f1-p1"),
              type: "text" as const,
              label: "Star 1",
              text: "✦",
              x: 30,
              y: 40,
              size: 10,
              color: "rgba(168,85,247,0.35)",
              animLoop: { type: "blsBreathing", dur: 2400, delay: 0 },
            },
            {
              id: id("cos-f1-p2"),
              type: "text" as const,
              label: "Star 2",
              text: "✧",
              x: 280,
              y: 140,
              size: 8,
              color: "rgba(56,189,248,0.30)",
              animLoop: { type: "blsFloat", dur: 2000, delay: 300 },
            },
            {
              id: id("cos-f1-p3"),
              type: "text" as const,
              label: "Hex",
              text: "⬡",
              x: 15,
              y: 420,
              size: 14,
              color: "rgba(244,114,182,0.25)",
              animLoop: { type: "blsSpin", dur: 8000, delay: 0 },
            },
            {
              id: id("cos-f1-p4"),
              type: "text" as const,
              label: "Diamond",
              text: "◇",
              x: 290,
              y: 30,
              size: 11,
              color: "rgba(168,85,247,0.28)",
              animLoop: { type: "blsPulseLoop", dur: 2600, delay: 500 },
            },
            // ── Content ──
            {
              id: id("cos-f1-qt"),
              type: "text" as const,
              label: "Q Counter",
              text: "01  /  03",
              x: 20,
              y: 24,
              size: 10,
              color: ACCENT2,
              letterSpacing: 4,
              fontWeight: "700",
              animIn: { type: "blsLightSpeedIn", dur: 500, delay: 100 },
            },
            {
              id: id("cos-f1-div1"),
              type: "divider" as const,
              label: "Top Divider",
              x: 20,
              y: 44,
              w: 280,
              thickness: 1,
              color: "rgba(168,85,247,0.20)",
              lineStyle: "dashed" as const,
              animIn: { type: "blsFadeIn", dur: 400, delay: 150 },
            },
            {
              id: id("cos-f1-q"),
              type: "text" as const,
              label: "Question",
              text: "What is the closest\nstar to Earth?",
              x: 20,
              y: 62,
              size: 24,
              color: "#ffffff",
              fontWeight: "800",
              lineHeight: 1.35,
              animIn: { type: "blsPerspectiveIn", dur: 700, delay: 200 },
            },
            {
              id: id("cos-f1-div2"),
              type: "divider" as const,
              label: "Mid Divider",
              x: 20,
              y: 140,
              w: 280,
              thickness: 1,
              color: "rgba(168,85,247,0.15)",
              lineStyle: "solid" as const,
            },
            {
              id: id("cos-f1-ans"),
              type: "answerGroup" as const,
              label: "Answers",
              x: 20,
              y: 160,
              w: 280,
              answers: [
                { id: id("cos-f1-a1"), text: "The Sun" },
                { id: id("cos-f1-a2"), text: "Proxima Centauri" },
                { id: id("cos-f1-a3"), text: "Alpha Centauri A" },
                { id: id("cos-f1-a4"), text: "Sirius" },
              ],
              btnHeight: 48,
              btnGap: 10,
              btnBgColor: ACCENT,
              btnBgOpacity: 14,
              btnRadius: 8,
              textColor: "#ffffff",
              fontSize: 15,
              role: "answer",
              animIn: {
                type: "blsSlideUp",
                dur: 400,
                delay: 250,
              },
              animOut: { type: "blsFadeOut", dur: 250 },
              hoverEffect: { type: "grow" },
              clickEffect: { type: "clickPop" },
            },
          ],
        },

        // ═══════════════════════════════════════════════════════════════════
        //  FRAME 2 — Question 2
        // ═══════════════════════════════════════════════════════════════════
        {
          id: id("cos-f2"),
          src: null,
          w: 320,
          h: 480,
          isDefault: false,
          isEndFrame: false,
          bgGradient: { angle: 200, stops: ["#070a20", "#15103a"] },
          animEnter: { type: "blsSlideUp", dur: 450 },
          animExit: { type: "blsFadeOut", dur: 300 },
          answerStagger: 90,
          objects: [
            // ── Decorative circles (shifted layout) ──
            {
              id: id("cos-f2-c1"),
              type: "shape" as const,
              shape: "circle" as const,
              label: "Orb Blue",
              x: 180,
              y: -50,
              w: 200,
              h: 200,
              fill: "rgba(56,189,248,0.07)",
              animLoop: { type: "blsFloat", dur: 3200, delay: 0 },
            },
            {
              id: id("cos-f2-c2"),
              type: "shape" as const,
              shape: "circle" as const,
              label: "Orb Purple",
              x: -60,
              y: 280,
              w: 190,
              h: 190,
              fill: "rgba(168,85,247,0.06)",
              animLoop: { type: "blsFloat", dur: 3800, delay: 600 },
            },
            {
              id: id("cos-f2-c3"),
              type: "shape" as const,
              shape: "circle" as const,
              label: "Orb Pink sm",
              x: 260,
              y: 400,
              w: 80,
              h: 80,
              fill: "rgba(244,114,182,0.06)",
              animLoop: { type: "blsHeartbeat", dur: 2200, delay: 300 },
            },
            // ── Accent bars (mirrored) ──
            {
              id: id("cos-f2-bar1"),
              type: "shape" as const,
              shape: "rect" as const,
              label: "Left Edge",
              x: 0,
              y: 0,
              w: 3,
              h: 480,
              fill: ACCENT2,
              animIn: { type: "blsSlideDown", dur: 500 },
            },
            {
              id: id("cos-f2-bar2"),
              type: "shape" as const,
              shape: "rect" as const,
              label: "Bottom Bar",
              x: 0,
              y: 477,
              w: 320,
              h: 3,
              fill: ACCENT,
            },
            {
              id: id("cos-f2-bar3"),
              type: "shape" as const,
              shape: "rect" as const,
              label: "Diagonal Accent 2",
              x: 10,
              y: 440,
              w: 50,
              h: 3,
              fill: ACCENT3,
              rotation: -30,
              opacity: 40,
              animIn: { type: "blsFadeIn", dur: 500, delay: 400 },
            },
            // ── Floating particles ──
            {
              id: id("cos-f2-p1"),
              type: "text" as const,
              label: "Star",
              text: "★",
              x: 290,
              y: 35,
              size: 9,
              color: "rgba(244,114,182,0.30)",
              animLoop: { type: "blsBreathing", dur: 2600, delay: 100 },
            },
            {
              id: id("cos-f2-p2"),
              type: "text" as const,
              label: "Sparkle",
              text: "✦",
              x: 25,
              y: 450,
              size: 12,
              color: "rgba(56,189,248,0.25)",
              animLoop: { type: "blsFloat", dur: 2400, delay: 200 },
            },
            {
              id: id("cos-f2-p3"),
              type: "text" as const,
              label: "Circle dot",
              text: "●",
              x: 300,
              y: 240,
              size: 6,
              color: "rgba(168,85,247,0.35)",
              animLoop: { type: "blsPulseLoop", dur: 2000, delay: 400 },
            },
            // ── Content ──
            {
              id: id("cos-f2-qt"),
              type: "text" as const,
              label: "Q Counter",
              text: "02  /  03",
              x: 20,
              y: 24,
              size: 10,
              color: ACCENT,
              letterSpacing: 4,
              fontWeight: "700",
              animIn: { type: "blsFadeIn", dur: 400, delay: 50 },
            },
            {
              id: id("cos-f2-div1"),
              type: "divider" as const,
              label: "Top Divider",
              x: 20,
              y: 44,
              w: 280,
              thickness: 1,
              color: "rgba(56,189,248,0.20)",
              lineStyle: "dashed" as const,
              animIn: { type: "blsFadeIn", dur: 300, delay: 100 },
            },
            {
              id: id("cos-f2-q"),
              type: "text" as const,
              label: "Question",
              text: "Which planet has the\nmost moons?",
              x: 20,
              y: 62,
              size: 24,
              color: "#ffffff",
              fontWeight: "800",
              lineHeight: 1.35,
              animIn: { type: "blsFlipIn", dur: 650, delay: 150 },
            },
            {
              id: id("cos-f2-div2"),
              type: "divider" as const,
              label: "Mid Divider",
              x: 20,
              y: 140,
              w: 280,
              thickness: 1,
              color: "rgba(56,189,248,0.12)",
              lineStyle: "solid" as const,
            },
            {
              id: id("cos-f2-ans"),
              type: "answerGroup" as const,
              label: "Answers",
              x: 20,
              y: 160,
              w: 280,
              answers: [
                { id: id("cos-f2-a1"), text: "Jupiter" },
                { id: id("cos-f2-a2"), text: "Saturn" },
                { id: id("cos-f2-a3"), text: "Uranus" },
                { id: id("cos-f2-a4"), text: "Neptune" },
              ],
              btnHeight: 48,
              btnGap: 10,
              btnBgColor: ACCENT2,
              btnBgOpacity: 12,
              btnRadius: 8,
              textColor: "#ffffff",
              fontSize: 15,
              role: "answer",
              animIn: {
                type: "blsSlideUp",
                dur: 400,
                delay: 200,
              },
              animOut: { type: "blsFadeOut", dur: 250 },
              hoverEffect: { type: "glow" },
              clickEffect: { type: "clickPulse" },
            },
          ],
        },

        // ═══════════════════════════════════════════════════════════════════
        //  FRAME 3 — Question 3
        // ═══════════════════════════════════════════════════════════════════
        {
          id: id("cos-f3"),
          src: null,
          w: 320,
          h: 480,
          isDefault: false,
          isEndFrame: false,
          bgGradient: { angle: 140, stops: ["#080614", "#1c0d38"] },
          animEnter: { type: "blsSlideLeft", dur: 450 },
          animExit: { type: "blsBlurOut", dur: 400 },
          answerStagger: 80,
          objects: [
            // ── Decorative circles ──
            {
              id: id("cos-f3-c1"),
              type: "shape" as const,
              shape: "circle" as const,
              label: "Orb Pink",
              x: 150,
              y: -40,
              w: 220,
              h: 220,
              fill: "rgba(244,114,182,0.06)",
              animLoop: { type: "blsFloat", dur: 3400, delay: 0 },
            },
            {
              id: id("cos-f3-c2"),
              type: "shape" as const,
              shape: "circle" as const,
              label: "Orb Purple",
              x: -80,
              y: 200,
              w: 160,
              h: 160,
              fill: "rgba(168,85,247,0.07)",
              animLoop: { type: "blsFloat", dur: 4000, delay: 300 },
            },
            {
              id: id("cos-f3-c3"),
              type: "shape" as const,
              shape: "circle" as const,
              label: "Heartbeat Orb",
              x: 240,
              y: 370,
              w: 100,
              h: 100,
              fill: "rgba(56,189,248,0.05)",
              animLoop: { type: "blsHeartbeat", dur: 2000, delay: 500 },
            },
            // ── Accent geometry ──
            {
              id: id("cos-f3-bar1"),
              type: "shape" as const,
              shape: "rect" as const,
              label: "Right Edge",
              x: 317,
              y: 0,
              w: 3,
              h: 480,
              fill: ACCENT3,
              animIn: { type: "blsSlideUp", dur: 500 },
            },
            {
              id: id("cos-f3-bar2"),
              type: "shape" as const,
              shape: "rect" as const,
              label: "Top Bar",
              x: 0,
              y: 0,
              w: 320,
              h: 3,
              fill: ACCENT,
            },
            {
              id: id("cos-f3-bar3"),
              type: "shape" as const,
              shape: "rect" as const,
              label: "Corner Accent",
              x: 250,
              y: 460,
              w: 70,
              h: 3,
              fill: ACCENT2,
              rotation: -45,
              opacity: 45,
              animIn: { type: "blsFadeIn", dur: 500, delay: 300 },
            },
            // ── Particles ──
            {
              id: id("cos-f3-p1"),
              type: "text" as const,
              label: "Hex spin",
              text: "⬡",
              x: 280,
              y: 50,
              size: 16,
              color: "rgba(168,85,247,0.22)",
              animLoop: { type: "blsSpin", dur: 10000, delay: 0 },
            },
            {
              id: id("cos-f3-p2"),
              type: "text" as const,
              label: "Sparkle",
              text: "✦",
              x: 18,
              y: 120,
              size: 10,
              color: "rgba(244,114,182,0.28)",
              animLoop: { type: "blsBreathing", dur: 2200, delay: 200 },
            },
            {
              id: id("cos-f3-p3"),
              type: "text" as const,
              label: "Triangle",
              text: "▸",
              x: 300,
              y: 300,
              size: 9,
              color: "rgba(56,189,248,0.30)",
              animLoop: { type: "blsSwing", dur: 2000, delay: 100 },
            },
            // ── Content ──
            {
              id: id("cos-f3-qt"),
              type: "text" as const,
              label: "Q Counter",
              text: "03  /  03",
              x: 20,
              y: 24,
              size: 10,
              color: ACCENT3,
              letterSpacing: 4,
              fontWeight: "700",
              animIn: { type: "blsFadeIn", dur: 400, delay: 50 },
            },
            {
              id: id("cos-f3-div1"),
              type: "divider" as const,
              label: "Top Divider",
              x: 20,
              y: 44,
              w: 280,
              thickness: 1,
              color: "rgba(244,114,182,0.20)",
              lineStyle: "dashed" as const,
              animIn: { type: "blsFadeIn", dur: 300, delay: 100 },
            },
            {
              id: id("cos-f3-q"),
              type: "text" as const,
              label: "Question",
              text: "How long does light\ntake to reach Earth\nfrom the Sun?",
              x: 20,
              y: 58,
              size: 22,
              color: "#ffffff",
              fontWeight: "800",
              lineHeight: 1.35,
              animIn: { type: "blsGlitchIn", dur: 600, delay: 150 },
            },
            {
              id: id("cos-f3-div2"),
              type: "divider" as const,
              label: "Mid Divider",
              x: 20,
              y: 148,
              w: 280,
              thickness: 1,
              color: "rgba(244,114,182,0.12)",
              lineStyle: "solid" as const,
            },
            {
              id: id("cos-f3-ans"),
              type: "answerGroup" as const,
              label: "Answers",
              x: 20,
              y: 168,
              w: 280,
              answers: [
                { id: id("cos-f3-a1"), text: "8 minutes" },
                { id: id("cos-f3-a2"), text: "4 minutes" },
                { id: id("cos-f3-a3"), text: "12 minutes" },
                { id: id("cos-f3-a4"), text: "1 minute" },
              ],
              btnHeight: 48,
              btnGap: 10,
              btnBgColor: ACCENT3,
              btnBgOpacity: 14,
              btnRadius: 8,
              textColor: "#ffffff",
              fontSize: 15,
              role: "answer",
              animIn: {
                type: "blsSlideUp",
                dur: 400,
                delay: 200,
              },
              animOut: { type: "blsFadeOut", dur: 250 },
              hoverEffect: { type: "lift" },
              clickEffect: { type: "clickJelly" },
            },
          ],
        },

        // ═══════════════════════════════════════════════════════════════════
        //  FRAME 4 — Thank You (End Frame)
        // ═══════════════════════════════════════════════════════════════════
        {
          id: id("cos-f4"),
          src: null,
          w: 320,
          h: 480,
          isDefault: false,
          isEndFrame: true,
          bgGradient: { angle: 170, stops: ["#0a0520", "#1a0a4a"] },
          animEnter: { type: "blsZoomIn", dur: 600 },
          animExit: { type: "blsFadeOut", dur: 300 },
          answerStagger: 0,
          objects: [
            // ── Many glowing orbs for celebration feel ──
            {
              id: id("cos-f4-c1"),
              type: "shape" as const,
              shape: "circle" as const,
              label: "Orb Purple lg",
              x: 60,
              y: -40,
              w: 220,
              h: 220,
              fill: "rgba(168,85,247,0.08)",
              animLoop: { type: "blsFloat", dur: 3500, delay: 0 },
            },
            {
              id: id("cos-f4-c2"),
              type: "shape" as const,
              shape: "circle" as const,
              label: "Orb Blue lg",
              x: -50,
              y: 300,
              w: 200,
              h: 200,
              fill: "rgba(56,189,248,0.07)",
              animLoop: { type: "blsFloat", dur: 4000, delay: 500 },
            },
            {
              id: id("cos-f4-c3"),
              type: "shape" as const,
              shape: "circle" as const,
              label: "Orb Pink md",
              x: 200,
              y: 320,
              w: 140,
              h: 140,
              fill: "rgba(244,114,182,0.06)",
              animLoop: { type: "blsPulseLoop", dur: 3000, delay: 300 },
            },
            {
              id: id("cos-f4-c4"),
              type: "shape" as const,
              shape: "circle" as const,
              label: "Orb accent sm",
              x: 240,
              y: 50,
              w: 80,
              h: 80,
              fill: "rgba(168,85,247,0.10)",
              animLoop: { type: "blsHeartbeat", dur: 2000, delay: 200 },
            },
            // ── Accent bars ──
            {
              id: id("cos-f4-bar1"),
              type: "shape" as const,
              shape: "rect" as const,
              label: "Top Bar",
              x: 0,
              y: 0,
              w: 320,
              h: 3,
              fill: ACCENT,
            },
            {
              id: id("cos-f4-bar2"),
              type: "shape" as const,
              shape: "rect" as const,
              label: "Bottom Bar",
              x: 0,
              y: 477,
              w: 320,
              h: 3,
              fill: ACCENT2,
            },
            // ── Confetti-like particles ──
            {
              id: id("cos-f4-p1"),
              type: "text" as const,
              label: "Star 1",
              text: "✦",
              x: 40,
              y: 80,
              size: 14,
              color: "rgba(168,85,247,0.40)",
              animLoop: { type: "blsBreathing", dur: 2200, delay: 0 },
              animIn: { type: "blsPopIn", dur: 400, delay: 200 },
            },
            {
              id: id("cos-f4-p2"),
              type: "text" as const,
              label: "Star 2",
              text: "★",
              x: 260,
              y: 110,
              size: 10,
              color: "rgba(244,114,182,0.35)",
              animLoop: { type: "blsFloat", dur: 2600, delay: 300 },
              animIn: { type: "blsPopIn", dur: 400, delay: 350 },
            },
            {
              id: id("cos-f4-p3"),
              type: "text" as const,
              label: "Diamond 1",
              text: "◆",
              x: 70,
              y: 360,
              size: 11,
              color: "rgba(56,189,248,0.30)",
              animLoop: { type: "blsPulseLoop", dur: 2400, delay: 100 },
              animIn: { type: "blsPopIn", dur: 400, delay: 500 },
            },
            {
              id: id("cos-f4-p4"),
              type: "text" as const,
              label: "Diamond 2",
              text: "◇",
              x: 240,
              y: 380,
              size: 9,
              color: "rgba(168,85,247,0.28)",
              animLoop: { type: "blsSwing", dur: 2800, delay: 400 },
              animIn: { type: "blsPopIn", dur: 400, delay: 600 },
            },
            {
              id: id("cos-f4-p5"),
              type: "text" as const,
              label: "Hex spin",
              text: "⬡",
              x: 150,
              y: 410,
              size: 18,
              color: "rgba(244,114,182,0.20)",
              animLoop: { type: "blsSpin", dur: 12000, delay: 0 },
              animIn: { type: "blsFadeIn", dur: 600, delay: 400 },
            },
            {
              id: id("cos-f4-p6"),
              type: "text" as const,
              label: "Sparkle 3",
              text: "✧",
              x: 25,
              y: 250,
              size: 8,
              color: "rgba(56,189,248,0.35)",
              animLoop: { type: "blsBreathing", dur: 2000, delay: 200 },
              animIn: { type: "blsPopIn", dur: 400, delay: 300 },
            },
            {
              id: id("cos-f4-p7"),
              type: "text" as const,
              label: "Dot",
              text: "●",
              x: 290,
              y: 260,
              size: 7,
              color: "rgba(168,85,247,0.32)",
              animLoop: { type: "blsPulseLoop", dur: 1800, delay: 600 },
              animIn: { type: "blsFadeIn", dur: 400, delay: 450 },
            },
            // ── Main content ──
            {
              id: id("cos-f4-h1"),
              type: "text" as const,
              label: "Thank You",
              text: "THANK\nYOU",
              x: 20,
              y: 140,
              w: 280,
              size: 72,
              color: "#ffffff",
              fontWeight: "900",
              lineHeight: 1.05,
              textAlign: "center" as const,
              letterSpacing: -2,
              animIn: {
                type: "blsElasticPop",
                dur: 800,
                delay: 100,
              },
              animLoop: { type: "blsPerspectiveTilt", dur: 4000, delay: 0 },
            },
            {
              id: id("cos-f4-div"),
              type: "divider" as const,
              label: "Divider",
              x: 110,
              y: 310,
              w: 100,
              thickness: 2,
              color: ACCENT,
              lineStyle: "solid" as const,
              animIn: { type: "blsFadeIn", dur: 400, delay: 500 },
            },
            {
              id: id("cos-f4-sub"),
              type: "text" as const,
              label: "Subtitle",
              text: "Your answers matter",
              x: 20,
              y: 328,
              w: 280,
              size: 14,
              color: "rgba(255,255,255,0.55)",
              textAlign: "center" as const,
              letterSpacing: 3,
              fontWeight: "500",
              animIn: { type: "blsFadeIn", dur: 500, delay: 600 },
            },
          ],
        },
      ],
    },
  },
};
