import type { Template } from "../_shared";
import { id } from "../_shared";

// ─────────────────────────────────────────────────────────────────────────────
//  Cyber Pulse — dark tech / gaming quiz
// ─────────────────────────────────────────────────────────────────────────────
export const cyberPulse: Template = {
  id: "cyber-pulse",
  name: "Cyber Pulse",
  description:
    "Dark tech aesthetic with cyan glow accents. Perfect for gaming, tech, or eSports quiz ads.",
  category: "quiz",
  tags: ["Quiz", "Tech", "Dark", "Gaming"],
  previewGradient: "linear-gradient(135deg, #050d1e 0%, #0a1628 100%)",
  accentColor: "#00e5ff",
  snapshot: {
    version: 1,
    defaultW: 320,
    defaultH: 480,
    currentPreviewIndex: 0,
    quizData: {
      bg: null,
      frames: [
        // ── Frame 1 — Intro splash ───────────────────────────────────────────
        {
          id: id("cp-f1"),
          src: null,
          w: 320,
          h: 480,
          isDefault: true,
          isEndFrame: false,
          bgGradient: { angle: 135, stops: ["#050d1e", "#0a1a3e"] },
          animEnter: { type: "blsFadeIn", dur: 500 },
          animExit: { type: "blsFadeOut", dur: 350 },
          answerStagger: 80,
          objects: [
            {
              id: id("cp-f1-o1"),
              type: "shape",
              shape: "rect",
              label: "Top Bar",
              x: 0,
              y: 0,
              w: 320,
              h: 4,
              fill: "#00e5ff",
            },
            {
              id: id("cp-f1-o2"),
              type: "shape",
              shape: "rect",
              label: "Bottom Bar",
              x: 0,
              y: 476,
              w: 320,
              h: 4,
              fill: "#00e5ff",
            },
            {
              id: id("cp-f1-o3"),
              type: "shape",
              shape: "circle",
              label: "Circle BG 1",
              x: 180,
              y: -60,
              w: 220,
              h: 220,
              fill: "rgba(0,229,255,0.06)",
            },
            {
              id: id("cp-f1-o4"),
              type: "shape",
              shape: "circle",
              label: "Circle BG 2",
              x: -80,
              y: 340,
              w: 240,
              h: 240,
              fill: "rgba(0,100,255,0.07)",
            },
            {
              id: id("cp-f1-o5"),
              type: "text",
              label: "Category Tag",
              text: "⬡  GAMING  ⬡",
              x: 0,
              y: 110,
              size: 11,
              color: "#00e5ff",
              textAlign: "center",
              letterSpacing: 4,
              fontWeight: "700",
              animIn: { type: "blsFadeIn", dur: 400, delay: 100 },
            },
            {
              id: id("cp-f1-o6"),
              type: "text",
              label: "Headline 1",
              text: "TECH",
              x: 0,
              y: 143,
              size: 86,
              color: "#ffffff",
              textAlign: "center",
              fontWeight: "900",
              letterSpacing: -2,
              animIn: { type: "blsSlideUp", dur: 500, delay: 150 },
            },
            {
              id: id("cp-f1-o7"),
              type: "text",
              label: "Headline 2",
              text: "QUIZ",
              x: 0,
              y: 230,
              size: 86,
              color: "#00e5ff",
              textAlign: "center",
              fontWeight: "900",
              letterSpacing: -2,
              animIn: { type: "blsSlideUp", dur: 500, delay: 250 },
            },
            {
              id: id("cp-f1-o8"),
              type: "divider",
              label: "Divider",
              x: 120,
              y: 328,
              w: 80,
              thickness: 1,
              color: "rgba(0,229,255,0.45)",
              lineStyle: "solid",
            },
            {
              id: id("cp-f1-o9"),
              type: "text",
              label: "Subtitle",
              text: "Test your knowledge",
              x: 0,
              y: 340,
              size: 14,
              color: "rgba(255,255,255,0.55)",
              textAlign: "center",
              letterSpacing: 2,
              animIn: { type: "blsFadeIn", dur: 400, delay: 400 },
            },
            {
              id: id("cp-f1-o10"),
              type: "text",
              label: "CTA",
              text: "TAP TO START  →",
              x: 0,
              y: 430,
              size: 12,
              color: "#00e5ff",
              textAlign: "center",
              letterSpacing: 3,
              fontWeight: "700",
              animIn: { type: "blsFadeIn", dur: 400, delay: 600 },
            },
          ],
        },
        // ── Frame 2 — Question ───────────────────────────────────────────────
        {
          id: id("cp-f2"),
          src: null,
          w: 320,
          h: 480,
          isDefault: false,
          isEndFrame: false,
          bgGradient: { angle: 135, stops: ["#050d1e", "#0a1a3e"] },
          animEnter: { type: "blsSlideUp", dur: 400 },
          animExit: { type: "blsFadeOut", dur: 300 },
          answerStagger: 90,
          objects: [
            {
              id: id("cp-f2-o1"),
              type: "shape",
              shape: "rect",
              label: "Edge Bar",
              x: 0,
              y: 0,
              w: 3,
              h: 480,
              fill: "#00e5ff",
            },
            {
              id: id("cp-f2-o2"),
              type: "shape",
              shape: "circle",
              label: "Circle BG",
              x: 190,
              y: -50,
              w: 200,
              h: 200,
              fill: "rgba(0,229,255,0.05)",
            },
            {
              id: id("cp-f2-o3"),
              type: "text",
              label: "Q Counter",
              text: "QUESTION  01  /  03",
              x: 20,
              y: 24,
              size: 10,
              color: "#00e5ff",
              letterSpacing: 3,
              fontWeight: "700",
              animIn: { type: "blsFadeIn", dur: 300 },
            },
            {
              id: id("cp-f2-o4"),
              type: "divider",
              label: "Top Divider",
              x: 20,
              y: 44,
              w: 280,
              thickness: 1,
              color: "rgba(0,229,255,0.18)",
              lineStyle: "solid",
            },
            {
              id: id("cp-f2-o5"),
              type: "text",
              label: "Question",
              text: "Which company develops\nthe Unreal Engine?",
              x: 20,
              y: 68,
              size: 22,
              color: "#ffffff",
              fontWeight: "700",
              lineHeight: 1.35,
              animIn: { type: "blsSlideUp", dur: 400, delay: 100 },
            },
            {
              id: id("cp-f2-o6"),
              type: "divider",
              label: "Mid Divider",
              x: 20,
              y: 148,
              w: 280,
              thickness: 1,
              color: "rgba(0,229,255,0.18)",
              lineStyle: "dashed",
            },
            {
              id: id("cp-f2-o7"),
              type: "answerGroup",
              label: "Answers",
              x: 20,
              y: 168,
              w: 280,
              answers: [
                { id: id("cp-f2-a1"), text: "Epic Games" },
                { id: id("cp-f2-a2"), text: "Unity Technologies" },
                { id: id("cp-f2-a3"), text: "CryTek" },
                { id: id("cp-f2-a4"), text: "id Software" },
              ],
              btnHeight: 48,
              btnGap: 10,
              btnBgColor: "#00e5ff",
              btnBgOpacity: 12,
              btnRadius: 6,
              textColor: "#ffffff",
              fontSize: 15,
              role: "answer",
              animIn: { type: "blsSlideUp", dur: 400, delay: 150 },
              animOut: { type: "blsFadeOut", dur: 300, delay: 0 },
            },
          ],
        },
      ],
    },
  },
};
