import type { Template } from "../_shared";
import { id } from "../_shared";

// ─────────────────────────────────────────────────────────────────────────────
//  Neon Aurora — entertainment / pop culture quiz
// ─────────────────────────────────────────────────────────────────────────────
export const neonAurora: Template = {
  id: "neon-aurora",
  name: "Neon Aurora",
  description:
    "Electric purple & pink neon vibes for pop culture, music, and entertainment quizzes.",
  category: "quiz",
  tags: ["Quiz", "Neon", "Entertainment", "Pop"],
  previewGradient: "linear-gradient(135deg, #0e0020 0%, #1a0040 100%)",
  accentColor: "#d946ef",
  snapshot: {
    version: 1,
    defaultW: 320,
    defaultH: 480,
    currentPreviewIndex: 0,
    quizData: {
      bg: null,
      frames: [
        // ── Frame 1 — Intro ──────────────────────────────────────────────────
        {
          id: id("na-f1"),
          src: null,
          w: 320,
          h: 480,
          isDefault: true,
          isEndFrame: false,
          bgGradient: { angle: 135, stops: ["#0e0020", "#1a0040"] },
          animEnter: { type: "blsFadeIn", dur: 500 },
          animExit: { type: "blsFadeOut", dur: 350 },
          answerStagger: 80,
          objects: [
            {
              id: id("na-f1-o1"),
              type: "shape",
              shape: "rect",
              label: "Top Bar",
              x: 0,
              y: 0,
              w: 320,
              h: 4,
              fill: "#d946ef",
            },
            {
              id: id("na-f1-o2"),
              type: "shape",
              shape: "circle",
              label: "Glow 1",
              x: 40,
              y: -80,
              w: 240,
              h: 240,
              fill: "rgba(139,92,246,0.12)",
            },
            {
              id: id("na-f1-o3"),
              type: "shape",
              shape: "circle",
              label: "Glow 2",
              x: 100,
              y: 320,
              w: 200,
              h: 200,
              fill: "rgba(217,70,239,0.10)",
            },
            {
              id: id("na-f1-o4"),
              type: "shape",
              shape: "circle",
              label: "Dot 1",
              x: 26,
              y: 26,
              w: 6,
              h: 6,
              fill: "#d946ef",
            },
            {
              id: id("na-f1-o5"),
              type: "shape",
              shape: "circle",
              label: "Dot 2",
              x: 288,
              y: 26,
              w: 6,
              h: 6,
              fill: "#a78bfa",
            },
            {
              id: id("na-f1-o6"),
              type: "text",
              label: "Tag",
              text: "✦  POP CULTURE  ✦",
              x: 0,
              y: 80,
              size: 11,
              color: "#d946ef",
              textAlign: "center",
              letterSpacing: 4,
              fontWeight: "700",
              animIn: { type: "blsFadeIn", dur: 400, delay: 0 },
            },
            {
              id: id("na-f1-o7"),
              type: "text",
              label: "Headline 1",
              text: "NEON",
              x: 0,
              y: 110,
              size: 90,
              color: "#d946ef",
              textAlign: "center",
              fontWeight: "900",
              letterSpacing: -2,
              animIn: { type: "blsSlideUp", dur: 500, delay: 100 },
            },
            {
              id: id("na-f1-o8"),
              type: "text",
              label: "Headline 2",
              text: "QUIZ",
              x: 0,
              y: 198,
              size: 90,
              color: "#ffffff",
              textAlign: "center",
              fontWeight: "900",
              letterSpacing: -2,
              animIn: { type: "blsSlideUp", dur: 500, delay: 200 },
            },
            {
              id: id("na-f1-o9"),
              type: "divider",
              label: "Divider",
              x: 100,
              y: 296,
              w: 120,
              thickness: 1,
              color: "rgba(217,70,239,0.4)",
              lineStyle: "solid",
            },
            {
              id: id("na-f1-o10"),
              type: "text",
              label: "Subtitle",
              text: "How well do you know\nyour pop culture?",
              x: 0,
              y: 308,
              size: 14,
              color: "rgba(255,255,255,0.5)",
              textAlign: "center",
              lineHeight: 1.5,
              animIn: { type: "blsFadeIn", dur: 400, delay: 350 },
            },
            {
              id: id("na-f1-o11"),
              type: "text",
              label: "Stars",
              text: "★  ★  ★  ★  ★",
              x: 0,
              y: 385,
              size: 14,
              color: "rgba(167,139,250,0.5)",
              textAlign: "center",
              animIn: { type: "blsFadeIn", dur: 400, delay: 400 },
            },
            {
              id: id("na-f1-o12"),
              type: "text",
              label: "CTA",
              text: "START QUIZ  ›",
              x: 0,
              y: 428,
              size: 13,
              color: "#d946ef",
              textAlign: "center",
              fontWeight: "800",
              letterSpacing: 2,
              animIn: { type: "blsFadeIn", dur: 400, delay: 550 },
            },
          ],
        },
        // ── Frame 2 — Question ───────────────────────────────────────────────
        {
          id: id("na-f2"),
          src: null,
          w: 320,
          h: 480,
          isDefault: false,
          isEndFrame: false,
          bgGradient: { angle: 135, stops: ["#0e0020", "#1a0040"] },
          animEnter: { type: "blsSlideUp", dur: 400 },
          animExit: { type: "blsFadeOut", dur: 300 },
          answerStagger: 90,
          objects: [
            {
              id: id("na-f2-o1"),
              type: "shape",
              shape: "rect",
              label: "Top Bar",
              x: 0,
              y: 0,
              w: 320,
              h: 4,
              fill: "#d946ef",
            },
            {
              id: id("na-f2-o2"),
              type: "shape",
              shape: "circle",
              label: "Glow",
              x: 140,
              y: -60,
              w: 180,
              h: 180,
              fill: "rgba(139,92,246,0.08)",
            },
            {
              id: id("na-f2-o3"),
              type: "shape",
              shape: "rect",
              label: "Right Accent",
              x: 317,
              y: 0,
              w: 3,
              h: 480,
              fill: "#a78bfa",
            },
            {
              id: id("na-f2-o4"),
              type: "text",
              label: "Category",
              text: "MUSIC",
              x: 20,
              y: 22,
              size: 10,
              color: "#a78bfa",
              letterSpacing: 4,
              fontWeight: "700",
              animIn: { type: "blsFadeIn", dur: 300 },
            },
            {
              id: id("na-f2-o5"),
              type: "divider",
              label: "Divider",
              x: 20,
              y: 42,
              w: 280,
              thickness: 1,
              color: "rgba(167,139,250,0.2)",
              lineStyle: "solid",
            },
            {
              id: id("na-f2-o6"),
              type: "text",
              label: "Question",
              text: "Which artist holds the record for the most Grammy wins?",
              x: 20,
              y: 60,
              size: 22,
              color: "#ffffff",
              fontWeight: "700",
              lineHeight: 1.35,
              animIn: { type: "blsSlideUp", dur: 450, delay: 100 },
            },
            {
              id: id("na-f2-o7"),
              type: "divider",
              label: "Ans Divider",
              x: 20,
              y: 164,
              w: 280,
              thickness: 1,
              color: "rgba(217,70,239,0.2)",
              lineStyle: "dashed",
            },
            {
              id: id("na-f2-o8"),
              type: "answerGroup",
              label: "Answers",
              x: 20,
              y: 180,
              w: 280,
              answers: [
                { id: id("na-f2-a1"), text: "Beyoncé" },
                { id: id("na-f2-a2"), text: "Taylor Swift" },
                { id: id("na-f2-a3"), text: "Michael Jackson" },
                { id: id("na-f2-a4"), text: "Jay-Z" },
              ],
              btnHeight: 48,
              btnGap: 10,
              btnBgColor: "#d946ef",
              btnBgOpacity: 13,
              btnRadius: 24,
              textColor: "#ffffff",
              fontSize: 15,
              role: "answer",
              animIn: { type: "blsSlideUp", dur: 450, delay: 200 },
              animOut: { type: "blsFadeOut", dur: 300, delay: 0 },
            },
          ],
        },
      ],
    },
  },
};
